// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezizqfnjuxxkjouofqja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6aXpxZm5qdXh4a2pvdW9mcWphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjY2NTAsImV4cCI6MjA2NTUwMjY1MH0.DAT-WlSSx8s0cQGe5GUPDKEXA60SslkG5rA2-XEGGXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);